# SPDX-License-Identifier: GPL-2.0-or-later
# Original handlers/reset compile unchanged, only in the differential test.
set(ioc02_classic_path "${PROJECT_SOURCE_DIR}/src/chipset/olivetti_ioc02.c")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ioc02_classic_path}")
file(READ "${ioc02_classic_path}" ioc02_classic)
string(REPLACE "\r\n" "\n" ioc02_classic "${ioc02_classic}")
string(SHA256 ioc02_hash "${ioc02_classic}")
if(NOT ioc02_hash STREQUAL "32c5a3e7bd04d670d3f1ca3aa01c7fdaf76cf9e2a0961e8776d9a6affa9a4506")
    message(FATAL_ERROR "IOC02 classic reference changed; review the port/oracle before updating its pinned hash")
endif()
function(ioc02_extract first last output)
    string(FIND "${ioc02_classic}" "${first}" begin)
    string(FIND "${ioc02_classic}" "${last}" end)
    if(begin LESS 0 OR end LESS_EQUAL begin)
        message(FATAL_ERROR "IOC02 classic fixture extraction boundary missing")
    endif()
    math(EXPR length "${end} - ${begin}")
    string(SUBSTRING "${ioc02_classic}" ${begin} ${length} body)
    set(${output} "${body}" PARENT_SCOPE)
endfunction()
ioc02_extract("/*\n * 86Box" "#include <stdarg.h>" notice)
ioc02_extract("typedef struct\n{" "/* Global handle" state)
ioc02_extract("static void\nolivetti_ioc02_write(" "static void\nolivetti_ioc02_close(" handlers)
ioc02_extract("static void\nolivetti_ioc02_reset(" "\nvoid\nolivetti_ioc02_set_first_read_hack(" reset)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/ioc02_classic_registers.inc"
    "/* SPDX-License-Identifier: GPL-2.0-or-later; generated test-only reference. */\n${notice}\n${state}\n${handlers}\n${reset}")
